### ISSUE TITLE
active users return empty set of data

### ISSUE THREAD

**Issue by camallen** [zooniverse/sugar#146] opened 2023-02-01 10:47 UTC
after #145 #141 and #139  we no longer see the list of active users returned from the API.

e.g. https://notifications-staging.zooniverse.org/active_users?channel=zooniverse

I think this may be due the following line where it's not using the redis `zscan` method for some reason, https://github.com/zooniverse/sugar/blob/b4f5ed076ace36e007933ecc4f5ecfcfbb0912aa/lib/presence.js#L73

https://github.com/zooniverse/sugar/pull/145#issuecomment-1411845042

**Comment by eatyourgreens** [comment] 2023-02-01 11:03
Is the key defined?

https://github.com/zooniverse/sugar/blob/b4f5ed076ace36e007933ecc4f5ecfcfbb0912aa/lib/presence.js#L100-L106

**Comment by eatyourgreens** [comment] 2023-02-01 11:20
Should be ok because those PRs are only on staging at the moment, until I’ve had a chance to test them on real projects. 

I’m probably back next week.

**Comment by eatyourgreens** [comment] 2023-02-01 13:13
I can't reproduce this on #148. The tests on that PR are also running `zscan` and reporting active users correctly.

There could be a bug in the Talk code where the browser calls the `/active_users` endpoint before the Sugar client has subscribed to the Talk channel. I'm not sure.

**Comment by eatyourgreens** [comment] 2023-02-01 13:19
I wasn't able to reproduce this on #148 so I'm going to see if I can reproduce it on staging.

**Comment by eatyourgreens** [comment] 2023-02-01 13:25
OK, confirmed with a logged-in user on https://master.pfe-preview.zooniverse.org/talk?env=staging

Now to figure out how to reproduce this locally. 🤔

**Comment by eatyourgreens** [comment] 2023-02-01 13:29
D'oh. `usersOn` returns an array of userIDs, not objects!

**Comment by eatyourgreens** [comment] 2023-02-01 13:43
Fixed by #149.

**Closed by eatyourgreens** 2023-02-01 13:43 UTC

**Comment by eatyourgreens** [comment] 2023-02-01 13:46
FWIW the clue to debugging this was that the tests for `presence.usersOn` were passing, so the bug had to be in `server.activeUsersAction`, where it parses that value.

**Comment by eatyourgreens** [comment] 2023-02-01 13:53
TODO: add some tests for the `/presence` and `/active_users` endpoints.
